### PR TITLE
frameworks/rust/mysql:  Add test case analogous to mysql_async case with Prisma failure

### PR DESCRIPTION
**Pull request by mcronce**

### CODE REVIEW

**Comment by deepthi** [comment]
This confused me at first. I think you mean `frameworks/rust/mysql` not `frameworks/rust/mysql_async` in the title.

**Comment by mcronce** [comment]
Whoops, sure do @deepthi :)

**Comment by harshit-gangal** [comment]
The tests are passing, do I assume this is working now?

**Comment by harshit-gangal** [comment]
I asking this because locally running this test, I am not seeing the error as well.

**Comment by mcronce** [comment]
@harshit-gangal this query works in `mysql`, it's only `mysql_async` where it fails - I added it here to test and made a PR because, well, the code was written, might as well add it to the repo :)

**Comment by mcronce** [comment]
OK, it now _also_ fails in this one.  I was missing almost the entire test case.  Protip:  Make sure you commit code instead of stashing it and jumping onto another task :)

**Review by skottler — APPROVED** [review]

**Pull request merged**
