### PR TITLE
Get php/laravel passing against upstream 5.7

### PR DESCRIPTION
**Pull request by skottler**
This pull request is intended to get the `php/laravel` framework passing against the 5.7 instance used in Actions today.

/cc https://github.com/planetscale/vitess-framework-testing/issues/48

### CODE REVIEW

**Comment by mcronce** [comment]
Does this work without the --env-file?  It was failing without that when I first put it together

**Comment by skottler** [comment]
The environment gets loaded from the workflow which overrides the environment file so it shouldn't be needed anymore.

Here's the output of a passing run in CI:

```
Successfully tagged php-laravel-framework-testing:latest
Migration table created successfully.
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > 
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (24.81ms)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (20.13ms)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (12.65ms)
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > 
Database seeding completed successfully.
php/laravel: 0
```

**Comment by mcronce** [comment]
Dope.  Looks like it's working fine in CI.  I'm always a fan of removing needless code ;)

Does it also work locally?

**Comment by skottler** [comment]
> Does it also work locally?

It seems fine as far as I can tell, I ran it locally with `VT_*` set and it works.

**Comment by mcronce** [comment]
Awesome.  SGTM

**Review by mcronce — APPROVED** [review]

**Pull request merged**
