### PR TITLE
Add tests covering the Active Record Validation section of the Rails guide

### PR DESCRIPTION
**Pull request by mcronce**
This isn't done yet; I just have it up here for visibility to the rest of the team

Also, it's branched from #111 instead of master - I'll rebase it when #111 is merged

### CODE REVIEW

**Comment by mcronce** [comment]
@skottler With #111 merged this is ready to review :)

**Comment by skottler** [comment]
@mcronce can you re-indent this to be two-spaces for a tab?

**Comment by mcronce** [comment]
@skottler Sure, but when did we adopt space indentation?  I've been using tabs from the get go

**Comment by skottler** [comment]
@mcronce ruby uses two spaces as a standard - it's documented [here](https://rubystyle.guide/#spaces-indentation). AFAIK there are no ruby files in this repo that use tabs.

**Comment by mcronce** [comment]
@skottler how important are language-specific conventions in a repo of tests written in a bunch of different languages?  There probably aren't in master, but there were in (at least) my PRs before spaces were requested, and it's only going to come up again and again when I add new files ;)

**Comment by skottler** [comment]
> how important are language-specific conventions in a repo of tests written in a bunch of different languages?

I don't feel very strongly about it, but my initial though is following upstream convention at least relatively closely is ideal. The biggest reason is that this more easily enables language or framewor experts to contribute. Following upstream style makes it easier for members of specific communities to jump in and make the relevant changes.

**Comment by mcronce** [comment]
@skottler Makes sense, either way I pushed the change up yesterday ;)

**Review by skottler — APPROVED** [review]

**Pull request merged**
