### PR TITLE
Set the timeout to 10 minutes

### PR DESCRIPTION
**Pull request by skottler**
This sets the timeout to be much more aggressive. The only case where this should be a problem is with Haskell stuff which often times out in general so this prevents it from burning a lot of compute along the way.

We'll want to implement image caching to support the Haskell case I think but curious to hear what you think @mcronce.

### CODE REVIEW

**Comment by mcronce** [comment]
So, I've thought about this to quite an extent :) and here's what I think our overall workflow should be
* Build container images in CI from this repo, and if possible, require this to succeed in order to merge a PR
  * I'm interested to hear your thoughts on a timeout for specifically the _build_ step - AFAIK Haskell images the only ones we have that exceed ten minutes, but there are some other fairly slow compiles (e.g. Rust).  There is the possibility of a network failure downloading dependencies causing compute resources to hang there forever doing nothing, so my gut feeling is "long timeout but not _no_ timeout"
* From this repo's CI, run the built images against MySQL and Vitess (open to opinions on version matrix), so we have results available immediately when a test is added/changed.  These runs should have a reasonably strict timeout, IMO - some of the failures I've seen in e.g. `mysqldump/export` have been hangs.  I've tried to make sure that I use `timeout` everywhere a hang is a likely failure mode, but having CI timeout to fall back on would be real good.
* From vitessio/vitess's CI, run the already-built images against Vitess.  Same timeout situation.

All that said, I think just adding an overall timeout like this is a perfectly reasonable first step, it just needs to be long enough to allow everything to build - and unfortunately, the Haskell ones do seem to just take that long based on local testing.

WDYT?

**Comment by skottler** [comment]
> Build container images in CI from this repo, and if possible, require this to succeed in order to merge a PR

What do you think about the concept of building images as their own build step with a much longer timeout? Then those can get pulled and immediately run rather than rebuilt over and over. We'll naturally get this benefit when the same image is run against different `vtgate`/`mysqld`'s in a single job, but building them ahead of time would let us pull instead of build that first image the majority of the time.

If we wind up caching images then we can likely get rid of this global timeout and use the approach mentioned of calling `timeout(1)` in individual cases.

**Comment by mcronce** [comment]
> What do you think about the concept of building images as their own build step with a much longer timeout?

That's exactly what I had in mind when I wrote that, so I like that concept a whole lot :)

**Comment by skottler** [comment]
Closing this for now since we've got a path to being able to get to a 10 minute timeout using intermediate layer caching.

**Pull request closed without merging**
