### PR TITLE
Skeema

### PR DESCRIPTION
**Pull request by mcronce**

### CODE REVIEW

**Comment by mcronce** [comment]
This isn't ready to go yet, got at least one issue left that looks like it'll take more than a few minutes to get fixed

**Comment by mcronce** [comment]
This is good to go; I'm filing a Vitess issue for the remaining failure now

**Comment by mcronce** [comment]
https://github.com/vitessio/vitess/issues/7687

**Comment by mcronce** [comment]
Fixes #64

**Review by skottler — APPROVED** [review]

**Pull request merged**
