### PR TITLE
Django models Refactoring for better readability

### PR DESCRIPTION
**Pull request by abhaykatheria**
organized models used by different tests in separate
folders.

Signed-off-by: abhaykatheria <abhay.katheria1998@gmail.com>

### CODE REVIEW

**Comment by mcronce** [comment]
@abhaykatheria  What do you think about calling the subpackages `fields`, `relationships`, and `crud` instead of `fields_models`, `relationships_models`, and `crud_models`?  IMO, this removes the redundancy from repeating "models" in e.g. `models.fields_models` without sacrificing any readability (`models.fields` still looks clear, to me at least), but I'm interested to hear your thoughts.

**Comment by abhaykatheria** [comment]
> 
> 
> @abhaykatheria What do you think about calling the subpackages `fields`, `relationships`, and `crud` instead of `fields_models`, `relationships_models`, and `crud_models`? IMO, this removes the redundancy from repeating "models" in e.g. `models.fields_models` without sacrificing any readability (`models.fields` still looks clear, to me at least), but I'm interested to hear your thoughts.

Just had the same thought I will change it asap 👍🏾

**Review by mcronce — APPROVED** [review]
LGTM :)

**Review by GuptaManan100 — APPROVED** [review]
Amazing. More readable 📖

**Pull request merged**
