### PR TITLE
+ frameworks/ruby/rails5

### PR DESCRIPTION
**Pull request by mcronce**
This ports the Rails 6 test to Rails 5

### CODE REVIEW

**Comment by skottler** [comment]
The changes introduced here look fine, but I think the test needs to get added to the definition so it'll run?

**Comment by mcronce** [comment]
Whoops, sure does.  Fixing now

**Comment by skottler** [comment]
The `ruby/rails5` suite fails right because of collation. Should this get overriden in `database.yml`?

```
Mysql2::Error: vtgate: http://psv2-frameworks-awsuseast1c1-vtgate-7dd937af-54647585c6-xxpbq:15000/: target: itest.-.master, used tablet: awsuseast1c1-3517409734 (10.8.145.219): vttablet: rpc error: code = InvalidArgument desc = Unknown collation: 'utf8_0900_ai_ci' (errno 1273) (sqlstate HY000) (CallerID: actions): Sql: "CREATE TABLE `schema_migrations` (`version` varchar(255) COLLATE utf8_0900_ai_ci NOT NULL PRIMARY KEY)", BindVars: ***
```

**Comment by mcronce** [comment]
@skottler I'm inclined to think we should consider that a compatibility issue and file it upstream.  @deepthi what do you think?  Should we consider a missing collation to be a test failure or just change the test?

**Review by skottler — APPROVED** [review]

**Pull request merged**
