### PR TITLE
Creating Cli to run framework tests

### PR DESCRIPTION
**Pull request by Akilan1999**
# Changes done
Bash scripts can get difficult as complexity of the program increases. As many of the recent pushes are converting frameworks run.sh in each directory to .py files. The cli is also made using python. At the moment docker builds as just running bash scripts. Once tests are logged rather than printed the docker python Api can be used to interact with the docker containers to handle errors better. 

#### Issue 
https://github.com/planetscale/vitess-framework-testing/issues/109

## Workflow
Location of python executables changed to directory 
```
tools/workflows
```

###  Commands
Runs all framework tests
```
--runall
```

Runs tests for only specific frameworks
```
--run_framework <framework name> or -runf <framework name>
```

Displays all frameworks available
```
--list_frameworks or -listf
```

Displays are docker images built with tag prefix vft-
```
--list_images or -listi
```

Displays all docker containers with tag prefix vft-
```
--list_contianers or -listc
```

### CODE REVIEW

**Comment by mcronce** [comment]
@skottler do you mind TAL?  These changes seem fine to me but you may have stronger opinions about the top-level automation :)

**Review by GuptaManan100 — COMMENTED** [review]
Would we also want to remove the run.sh file? Its work is now being done by your bash script right

**Comment by Akilan1999** [comment]
> 
> 
> Would we also want to remove the run.sh file? Its work is now being done by your bash script right

@GuptaManan100 the bash scritps are still being used in the github workflows

**Comment by GuptaManan100** [comment]
@Akilan1999  is there a way to change that too so that we only have 1 place where the logic lives.

**Comment by mcronce** [comment]
@GuptaManan100 @Akilan1999 I'm 100% comfortable merging with the bash still alive nad taking care of porting the workflows myself so we can remove the bash :)

**Comment by Akilan1999** [comment]
Just want to clarify is there anything missing from this pull request from being merged

**Comment by Akilan1999** [comment]
> @Akilan1999 is there a way to change that too so that we only have 1 place where the logic lives?

Yes there is and we can address it as another issue.

**Review by skottler — CHANGES_REQUESTED** [review]
I'm not sure this change is one that makes sense for this repository - has it been discussed elsewhere before this pull request?

The biggest reason I'd prefer to leave the tooling in bash is that it prevents this mix of shelling out, calling arbitrary scripts, and "bashy python." This makes the repository more difficult to maintain, the footprint of the tooling larger than it needs to be, and it requires lots of additional environment configuration.

If there are specific issues that should get fixed it is worth addressing those individually.

**Comment by Akilan1999** [comment]
I had a discussion with Andres and Manan regarding converting the bash scripts to another language because the more functionality we want in the .sh file. The more difficult it's to add. 
The initial plan was to build it using Go.
Because the Rails guide testing is done using python. I planned to stick to python even for the commands. 

@skottler I would agree with your point. The plan was only temporary to use bash scripts inside for running docker images (It is much better move to use the Docker python library). The reason the docker library in python was not used for build and run was due to the fact that the rails tests are only printed and not logged yet. 

The points above are the main reasons behind this pull request

**Comment by skottler** [comment]
> regarding converting the bash scripts to another language because the more functionality we want in the .sh file. The more difficult it's to add.

The easiest way to fix this problem is to break out the monolithic script into several different scripts and share a small set of helpers between them. In the context of the things added in this pull request you'd have tools like `script/list_frameworks` or `script/list_images` instead of one script that accepts flags.

At the very least it would be better to replace each `os.system` invocation with library usage. Even still I feel that keeping this tooling as simple as possible is beneficial and avoiding having to bootstrap a virtualenv, install dependencies, and then utilize that virtualenv to be able to use it seems beneficial. That is particularly true if the python is primarily shelling out.

**Comment by Akilan1999** [comment]
Agreed,
I will just convert all the functonalities to a bash script instead. As adding a virtualenv is way too heavy for the intended functionality

**Pull request closed without merging**
