### PR TITLE
+ .github/workflows/test-all.yml

### PR DESCRIPTION
**Pull request by mcronce**

### CODE REVIEW

**Comment by mcronce** [comment]
Hah, I can't test this until it's merged.  YOLO

**Comment by deepthi** [comment]
> Hah, I can't test this until it's merged. YOLO

Yes you can.
https://github.com/planetscale/vitess-framework-testing/actions?query=branch%3Avitess-image-workflow-parameter

**Comment by mcronce** [comment]
@deepthi those test runs are for the standard PR CI, not for the new trigger-on-demand stuff :(

**Review by skottler — APPROVED** [review]

**Comment by mcronce** [comment]
Merging so we can test and iterate if needed

**Pull request merged**
